### ISSUE TITLE
create some publishing lifecycle to make imports more reliable

### ISSUE THREAD

**Issue by NikoBergemann** [upb-uc4/hlf-api#32]
**Is your feature request related to a problem? Please describe.**
Regular github-clone-import on lagoms build.sbt causes problems on the pipeline

**Describe the solution you'd like**
The hlf-api shall be importable via the regular sbt version import 

**Describe alternatives you've considered**
Let Lagom figure it out --> should not push effort to customers

**Comment by david-buderus** [comment]
Our current approach in including this into lagom-core, destroys from time to time our build.
We need another way to import your project.

**Comment by NikoBergemann** [comment]
- [ ] Register to Sonatype (for credentials in teams)
- [ ] Prove ownership of domain (Redirect from domain to github)
- [ ] set up .sbt for publishing in sonatype
- [ ] manual publication test
- [ ] Pipeline for automatic deployment (manual or by new tag)

**Comment by NikoBergemann** [comment]
https://github.com/upb-uc4/hlf-api/actions/runs/319828679
