### ISSUE TITLE
Change project name in build.sbt to hlf-api

### ISSUE THREAD

**Issue by palkra** [upb-uc4/hlf-api#64]
**Is your feature request related to a problem? Please describe.**
We renamed the repository to hlf-api, but the name in the `build.sbt` is still hyperledger_api.

**Describe the solution you'd like**
Change it to hlf-api.

**Describe alternatives you've considered**
If there are no severe side effects, rename it .

**Comment by NikoBergemann** [comment]
Cannot rename the lazy val, because sbt does not allow such variableNames. Maybe we can remove the project object and instead just configure the build SBT as root
