### ISSUE TITLE
Test cases should have timeouts

### ISSUE THREAD

**Issue by this-kramer** [upb-uc4/hlf-api#77]
**Is your feature request related to a problem? Please describe.**
Test cases don't fail but run nearly forever.
![image](https://user-images.githubusercontent.com/25657304/97428331-21aea280-1916-11eb-8ad3-6698f6958fb6.png)

**Describe the solution you'd like**
Test cases should have timeouts or a maximum number of retries before they fail.

**Comment by NikoBergemann** [comment]
in case of no network beeing provided, tests time out already

need to wrap chain access with timeout functionality when "successfully" communicating so that waiting for peer response does not cause these extensive waiting times

**Comment by NikoBergemann** [comment]
@this-kramer 
Has this already been fixed by the timeout in the networkDescription/connectionProfile?

**Comment by this-kramer** [comment]
I think the timeouts in the connection profile do not affect this issue, since they were present when this behavior occured.
